twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        project_image_dir: 'uploads/images/project/'

when@test:
    twig:
        strict_variables: true
